#############################################################################
# Makefile for building: unix/cuberok
# Generated by qmake (2.01a) (Qt 4.3.4) on: ?? ???? 14 12:17:49 2008
# Project:  Cuberok.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Cuberok.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAUDIERE -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -I/usr/include/taglib -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -I/usr/include/taglib -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include/QtSql -I/usr/lib/qt4/include/QtSql -I/usr/lib/qt4/include -I-I/usr/local/include -Iunix/obj -Isrc
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt4/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4/lib -L/usr/local/lib -laudiere -ltag -lQtSql -L/usr/lib -L/usr/lib/qt4/lib -lQtGui -L/usr/X11R6/lib -lpng -lSM -lICE -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = unix/obj/

####### Files

SOURCES       = src/aboutdialog.cpp \
		src/collectionview.cpp \
		src/cuberok.cpp \
		src/database.cpp \
		src/indicator.cpp \
		src/lookandfeel.cpp \
		src/main.cpp \
		src/player.cpp \
		src/playlistcontainer.cpp \
		src/playlistmodel.cpp \
		src/playlistsettings.cpp \
		src/playlistview.cpp \
		src/progressbar.cpp \
		src/stardelegate.cpp \
		src/stareditor.cpp \
		src/starrating.cpp \
		src/tageditor.cpp \
		src/tagger.cpp unix/obj/moc_aboutdialog.cpp \
		unix/obj/moc_collectionview.cpp \
		unix/obj/moc_cuberok.cpp \
		unix/obj/moc_indicator.cpp \
		unix/obj/moc_lookandfeel.cpp \
		unix/obj/moc_player.cpp \
		unix/obj/moc_playlistcontainer.cpp \
		unix/obj/moc_playlistmodel.cpp \
		unix/obj/moc_playlistsettings.cpp \
		unix/obj/moc_playlistview.cpp \
		unix/obj/moc_progressbar.cpp \
		unix/obj/moc_stardelegate.cpp \
		unix/obj/moc_stareditor.cpp \
		unix/obj/moc_tageditor.cpp \
		unix/obj/qrc_resource.cpp
OBJECTS       = unix/obj/aboutdialog.o \
		unix/obj/collectionview.o \
		unix/obj/cuberok.o \
		unix/obj/database.o \
		unix/obj/indicator.o \
		unix/obj/lookandfeel.o \
		unix/obj/main.o \
		unix/obj/player.o \
		unix/obj/playlistcontainer.o \
		unix/obj/playlistmodel.o \
		unix/obj/playlistsettings.o \
		unix/obj/playlistview.o \
		unix/obj/progressbar.o \
		unix/obj/stardelegate.o \
		unix/obj/stareditor.o \
		unix/obj/starrating.o \
		unix/obj/tageditor.o \
		unix/obj/tagger.o \
		unix/obj/moc_aboutdialog.o \
		unix/obj/moc_collectionview.o \
		unix/obj/moc_cuberok.o \
		unix/obj/moc_indicator.o \
		unix/obj/moc_lookandfeel.o \
		unix/obj/moc_player.o \
		unix/obj/moc_playlistcontainer.o \
		unix/obj/moc_playlistmodel.o \
		unix/obj/moc_playlistsettings.o \
		unix/obj/moc_playlistview.o \
		unix/obj/moc_progressbar.o \
		unix/obj/moc_stardelegate.o \
		unix/obj/moc_stareditor.o \
		unix/obj/moc_tageditor.o \
		unix/obj/qrc_resource.o
DIST          = /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		Cuberok.pro
QMAKE_TARGET  = cuberok
DESTDIR       = unix/
TARGET        = unix/cuberok

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui_aboutdialog.h src/ui_collectionview.h src/ui_cuberok.h src/ui_lookandfeel.h src/ui_tageditor.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) unix/ || $(MKDIR) unix/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Cuberok.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/lib/libQtSql.prl \
		/usr/lib/qt4/lib/libQtCore.prl \
		/usr/lib/qt4/lib/libQtGui.prl
	$(QMAKE) -unix -o Makefile Cuberok.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/lib/libQtSql.prl:
/usr/lib/qt4/lib/libQtCore.prl:
/usr/lib/qt4/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Cuberok.pro

dist: 
	@$(CHK_DIR_EXISTS) unix/obj/cuberok1.0.0 || $(MKDIR) unix/obj/cuberok1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) unix/obj/cuberok1.0.0/ && $(COPY_FILE) --parents src/aboutdialog.h src/collectionview.h src/cuberok.h src/database.h src/indicator.h src/lookandfeel.h src/main.h src/player.h src/playlistcontainer.h src/playlistmodel.h src/playlistsettings.h src/playlistview.h src/progressbar.h src/stardelegate.h src/stareditor.h src/starrating.h src/tageditor.h src/tagger.h unix/obj/cuberok1.0.0/ && $(COPY_FILE) --parents src/resource.qrc unix/obj/cuberok1.0.0/ && $(COPY_FILE) --parents src/aboutdialog.cpp src/collectionview.cpp src/cuberok.cpp src/database.cpp src/indicator.cpp src/lookandfeel.cpp src/main.cpp src/player.cpp src/playlistcontainer.cpp src/playlistmodel.cpp src/playlistsettings.cpp src/playlistview.cpp src/progressbar.cpp src/stardelegate.cpp src/stareditor.cpp src/starrating.cpp src/tageditor.cpp src/tagger.cpp unix/obj/cuberok1.0.0/ && $(COPY_FILE) --parents src/aboutdialog.ui src/collectionview.ui src/cuberok.ui src/lookandfeel.ui src/tageditor.ui unix/obj/cuberok1.0.0/ && $(COPY_FILE) --parents cuberok_ru.ts unix/obj/cuberok1.0.0/ && (cd `dirname unix/obj/cuberok1.0.0` && $(TAR) cuberok1.0.0.tar cuberok1.0.0 && $(COMPRESS) cuberok1.0.0.tar) && $(MOVE) `dirname unix/obj/cuberok1.0.0`/cuberok1.0.0.tar.gz . && $(DEL_FILE) -r unix/obj/cuberok1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: unix/obj/moc_aboutdialog.cpp unix/obj/moc_collectionview.cpp unix/obj/moc_cuberok.cpp unix/obj/moc_indicator.cpp unix/obj/moc_lookandfeel.cpp unix/obj/moc_player.cpp unix/obj/moc_playlistcontainer.cpp unix/obj/moc_playlistmodel.cpp unix/obj/moc_playlistsettings.cpp unix/obj/moc_playlistview.cpp unix/obj/moc_progressbar.cpp unix/obj/moc_stardelegate.cpp unix/obj/moc_stareditor.cpp unix/obj/moc_tageditor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) unix/obj/moc_aboutdialog.cpp unix/obj/moc_collectionview.cpp unix/obj/moc_cuberok.cpp unix/obj/moc_indicator.cpp unix/obj/moc_lookandfeel.cpp unix/obj/moc_player.cpp unix/obj/moc_playlistcontainer.cpp unix/obj/moc_playlistmodel.cpp unix/obj/moc_playlistsettings.cpp unix/obj/moc_playlistview.cpp unix/obj/moc_progressbar.cpp unix/obj/moc_stardelegate.cpp unix/obj/moc_stareditor.cpp unix/obj/moc_tageditor.cpp
unix/obj/moc_aboutdialog.cpp: src/ui_aboutdialog.h \
		src/aboutdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/aboutdialog.h -o unix/obj/moc_aboutdialog.cpp

unix/obj/moc_collectionview.cpp: src/ui_collectionview.h \
		src/collectionview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/collectionview.h -o unix/obj/moc_collectionview.cpp

unix/obj/moc_cuberok.cpp: src/ui_cuberok.h \
		src/collectionview.h \
		src/ui_collectionview.h \
		src/playlistcontainer.h \
		src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/progressbar.h \
		src/cuberok.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/cuberok.h -o unix/obj/moc_cuberok.cpp

unix/obj/moc_indicator.cpp: src/indicator.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/indicator.h -o unix/obj/moc_indicator.cpp

unix/obj/moc_lookandfeel.cpp: src/ui_lookandfeel.h \
		src/lookandfeel.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/lookandfeel.h -o unix/obj/moc_lookandfeel.cpp

unix/obj/moc_player.cpp: src/main.h \
		src/player.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/player.h -o unix/obj/moc_player.cpp

unix/obj/moc_playlistcontainer.cpp: src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/playlistcontainer.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/playlistcontainer.h -o unix/obj/moc_playlistcontainer.cpp

unix/obj/moc_playlistmodel.cpp: src/playlistmodel.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/playlistmodel.h -o unix/obj/moc_playlistmodel.cpp

unix/obj/moc_playlistsettings.cpp: src/playlistmodel.h \
		src/playlistsettings.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/playlistsettings.h -o unix/obj/moc_playlistsettings.cpp

unix/obj/moc_playlistview.cpp: src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/playlistview.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/playlistview.h -o unix/obj/moc_playlistview.cpp

unix/obj/moc_progressbar.cpp: src/progressbar.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/progressbar.h -o unix/obj/moc_progressbar.cpp

unix/obj/moc_stardelegate.cpp: src/stardelegate.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/stardelegate.h -o unix/obj/moc_stardelegate.cpp

unix/obj/moc_stareditor.cpp: src/starrating.h \
		src/stareditor.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/stareditor.h -o unix/obj/moc_stareditor.cpp

unix/obj/moc_tageditor.cpp: src/ui_tageditor.h \
		src/tageditor.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/tageditor.h -o unix/obj/moc_tageditor.cpp

compiler_rcc_make_all: unix/obj/qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) unix/obj/qrc_resource.cpp
unix/obj/qrc_resource.cpp: src/resource.qrc \
		images/star2s.png \
		images/MatieresExplosives.png \
		images/rating1.png \
		images/rating5.png \
		images/emblem-distinguished.png \
		images/rating4.png \
		images/gray_pause.png \
		images/addtab.png \
		images/stock_person.png \
		images/emblem-noread.png \
		images/rating3.png \
		images/closetab.png \
		images/gnome-dev-cdrom-audio.png \
		images/gray_stop.png \
		images/gray_backward.png \
		images/gray_play.png \
		images/gnome-audio.png \
		images/rating2.png \
		images/gray_forward.png \
		images/gnome-cdplayer-icon.png \
		images/s_check_off.png \
		images/stock_notes.png
	/usr/lib/qt4/bin/rcc -name resource src/resource.qrc -o unix/obj/qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui_aboutdialog.h src/ui_collectionview.h src/ui_cuberok.h src/ui_lookandfeel.h src/ui_tageditor.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui_aboutdialog.h src/ui_collectionview.h src/ui_cuberok.h src/ui_lookandfeel.h src/ui_tageditor.h
src/ui_aboutdialog.h: src/aboutdialog.ui
	/usr/lib/qt4/bin/uic src/aboutdialog.ui -o src/ui_aboutdialog.h

src/ui_collectionview.h: src/collectionview.ui
	/usr/lib/qt4/bin/uic src/collectionview.ui -o src/ui_collectionview.h

src/ui_cuberok.h: src/cuberok.ui
	/usr/lib/qt4/bin/uic src/cuberok.ui -o src/ui_cuberok.h

src/ui_lookandfeel.h: src/lookandfeel.ui
	/usr/lib/qt4/bin/uic src/lookandfeel.ui -o src/ui_lookandfeel.h

src/ui_tageditor.h: src/tageditor.ui
	/usr/lib/qt4/bin/uic src/tageditor.ui -o src/ui_tageditor.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

unix/obj/aboutdialog.o: src/aboutdialog.cpp src/aboutdialog.h \
		src/ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/aboutdialog.o src/aboutdialog.cpp

unix/obj/collectionview.o: src/collectionview.cpp src/collectionview.h \
		src/ui_collectionview.h \
		src/database.h \
		src/tagger.h \
		src/indicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/collectionview.o src/collectionview.cpp

unix/obj/cuberok.o: src/cuberok.cpp src/cuberok.h \
		src/ui_cuberok.h \
		src/collectionview.h \
		src/ui_collectionview.h \
		src/playlistcontainer.h \
		src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/progressbar.h \
		src/aboutdialog.h \
		src/ui_aboutdialog.h \
		src/lookandfeel.h \
		src/ui_lookandfeel.h \
		src/tagger.h \
		src/playlistsettings.h \
		src/indicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/cuberok.o src/cuberok.cpp

unix/obj/database.o: src/database.cpp src/database.h \
		src/main.h \
		src/tagger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/database.o src/database.cpp

unix/obj/indicator.o: src/indicator.cpp src/indicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/indicator.o src/indicator.cpp

unix/obj/lookandfeel.o: src/lookandfeel.cpp src/lookandfeel.h \
		src/ui_lookandfeel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/lookandfeel.o src/lookandfeel.cpp

unix/obj/main.o: src/main.cpp src/cuberok.h \
		src/ui_cuberok.h \
		src/collectionview.h \
		src/ui_collectionview.h \
		src/playlistcontainer.h \
		src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/progressbar.h \
		src/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/main.o src/main.cpp

unix/obj/player.o: src/player.cpp src/player.h \
		src/main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/player.o src/player.cpp

unix/obj/playlistcontainer.o: src/playlistcontainer.cpp src/playlistcontainer.h \
		src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/playlistsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/playlistcontainer.o src/playlistcontainer.cpp

unix/obj/playlistmodel.o: src/playlistmodel.cpp src/playlistmodel.h \
		src/main.h \
		src/database.h \
		src/tagger.h \
		src/starrating.h \
		src/indicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/playlistmodel.o src/playlistmodel.cpp

unix/obj/playlistsettings.o: src/playlistsettings.cpp src/playlistsettings.h \
		src/playlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/playlistsettings.o src/playlistsettings.cpp

unix/obj/playlistview.o: src/playlistview.cpp src/playlistview.h \
		src/playlistmodel.h \
		src/player.h \
		src/main.h \
		src/tageditor.h \
		src/ui_tageditor.h \
		src/tagger.h \
		src/database.h \
		src/stardelegate.h \
		src/starrating.h \
		src/playlistsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/playlistview.o src/playlistview.cpp

unix/obj/progressbar.o: src/progressbar.cpp src/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/progressbar.o src/progressbar.cpp

unix/obj/stardelegate.o: src/stardelegate.cpp src/stardelegate.h \
		src/stareditor.h \
		src/starrating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/stardelegate.o src/stardelegate.cpp

unix/obj/stareditor.o: src/stareditor.cpp src/stareditor.h \
		src/starrating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/stareditor.o src/stareditor.cpp

unix/obj/starrating.o: src/starrating.cpp src/starrating.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/starrating.o src/starrating.cpp

unix/obj/tageditor.o: src/tageditor.cpp src/tageditor.h \
		src/ui_tageditor.h \
		src/main.h \
		src/tagger.h \
		src/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/tageditor.o src/tageditor.cpp

unix/obj/tagger.o: src/tagger.cpp src/tagger.h \
		src/main.h \
		src/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/tagger.o src/tagger.cpp

unix/obj/moc_aboutdialog.o: unix/obj/moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_aboutdialog.o unix/obj/moc_aboutdialog.cpp

unix/obj/moc_collectionview.o: unix/obj/moc_collectionview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_collectionview.o unix/obj/moc_collectionview.cpp

unix/obj/moc_cuberok.o: unix/obj/moc_cuberok.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_cuberok.o unix/obj/moc_cuberok.cpp

unix/obj/moc_indicator.o: unix/obj/moc_indicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_indicator.o unix/obj/moc_indicator.cpp

unix/obj/moc_lookandfeel.o: unix/obj/moc_lookandfeel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_lookandfeel.o unix/obj/moc_lookandfeel.cpp

unix/obj/moc_player.o: unix/obj/moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_player.o unix/obj/moc_player.cpp

unix/obj/moc_playlistcontainer.o: unix/obj/moc_playlistcontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_playlistcontainer.o unix/obj/moc_playlistcontainer.cpp

unix/obj/moc_playlistmodel.o: unix/obj/moc_playlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_playlistmodel.o unix/obj/moc_playlistmodel.cpp

unix/obj/moc_playlistsettings.o: unix/obj/moc_playlistsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_playlistsettings.o unix/obj/moc_playlistsettings.cpp

unix/obj/moc_playlistview.o: unix/obj/moc_playlistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_playlistview.o unix/obj/moc_playlistview.cpp

unix/obj/moc_progressbar.o: unix/obj/moc_progressbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_progressbar.o unix/obj/moc_progressbar.cpp

unix/obj/moc_stardelegate.o: unix/obj/moc_stardelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_stardelegate.o unix/obj/moc_stardelegate.cpp

unix/obj/moc_stareditor.o: unix/obj/moc_stareditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_stareditor.o unix/obj/moc_stareditor.cpp

unix/obj/moc_tageditor.o: unix/obj/moc_tageditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/moc_tageditor.o unix/obj/moc_tageditor.cpp

unix/obj/qrc_resource.o: unix/obj/qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unix/obj/qrc_resource.o unix/obj/qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

