######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 2 16:36:07 2008
######################################################################

TEMPLATE = app
TARGET = test-mime
DEPENDPATH += .
INCLUDEPATH += .

QT += xml

# Input
HEADERS += src/freedesktopmime.h
SOURCES += src/freedesktopmime.cpp src/test.cpp
RESOURCES += freedesktopmime.qrc
