Document: cuberok
Title: Debian cuberok Manual
Author: <insert document author here>
Abstract: This manual describes what cuberok is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cuberok/cuberok.sgml.gz

Format: postscript
Files: /usr/share/doc/cuberok/cuberok.ps.gz

Format: text
Files: /usr/share/doc/cuberok/cuberok.text.gz

Format: HTML
Index: /usr/share/doc/cuberok/html/index.html
Files: /usr/share/doc/cuberok/html/*.html


